### PR TITLE
Pairing Authorisation verification when fetched from file server

### PR DESCRIPTION
**Pull request by Mikunj**

### CODE REVIEW

**Comment by neuroscr** [comment]
Why only verifying one side? Shouldn't it check that both pubKeys are in agreement and then you can just use `window.lokiFileServerAPI.verifyUserObjectDeviceMap`

Also why is it being done singly by pubKey, this is going to be slow, we need to batch all the pubkeys you want to look up at once and then submit the request?

**Comment by Mikunj** [comment]
> Why only verifying one side? Shouldn't it check that both pubKeys are in agreement (and then you can just use the same infrastructure in `window.lokiFileServerAPI` that open group uses)

What do you mean by this?

> Also why is it being done singly by pubKey, this is going to be slow, we need to batch all the pubkeys you want to look up at once and then submit the request?

Because we need the mappings straight away otherwise we can run into a situation where the multidevice states are out of sync just because we're waiting to batch a bunch of them.

**Comment by neuroscr** [comment]
> What do you mean by this?
You have to pull the primary and secondary pubkeys from the fileserver and verify both side of the authorisation. An unlinked secondary device could have its outdating mapping on the file server still because it hasn't received the unlink message yet. (only the Primary and new secondary would be up to date but the old secondary, if malicious and ignored the unlink message, would still be able to send as primary until it cleared it's mapping)

**Comment by Mikunj** [comment]
> You have to pull the primary and secondary pubkeys from the fileserver and verify both side of the authorisation. An unlinked secondary device could have its outdating mapping on the file server still because it hasn't received the unlink message yet. (only the Primary and new secondary would be up to date but the old secondary, if malicious and ignored the unlink message, would still be able to send as primary until it cleared it's mapping)

We can do that but it'll just introduce a lot of delays when fetching mappings which i'm trying to avoid.

> I think that happens no matter what. We should plan defensively against that.

In the current system it will happen less as we always fetch a mapping for a user every X amount of time. We could maybe batch those requests but the initial request should not be batched as we want the mapping straight away.

**Pull request merged**
