### PR TITLE
Fix messages not being created properly in open groups

### PR DESCRIPTION
**Pull request by Mikunj**
This seemed to be a bug introduced with a previous bug fix in which message decryption was sped up.

Old PR: #976 

Also fixed up bugs which occurred when an invalid authorisation was passed.

### CODE REVIEW

**Comment by neuroscr** [comment]
Just to keep this extra documentation I got about the PR in DMs:
```
[10:21 PM] Mikunj: Before the initial refactor, we were fetching the devices first and then it was going into the if statement, but it had the condition to only go in if our device was in the device list
[10:21 PM] Mikunj: i removed this condition and moved it into the if statement itself so we don't fetch our pairing unnecessarily
[10:22 PM] Mikunj: but this basically meant that all open group messages went inside the condition
[10:22 PM] Mikunj: and when they did, all messages which don't return true on if (source && (source === ourNumber || source === primaryDevice)) { will have message set to null
[10:22 PM] Mikunj: which then broke the rest of the logic
```

**Comment by Mikunj** [comment]
Actually, since we are now just getting our number and our primary device from storage, there's no need to the previous PR change so I can revert it back to what it was without affecting performance. That might make the code more clearer?

**Comment by neuroscr** [comment]
what code changed the the getting number/primary device?

**Comment by Mikunj** [comment]
We used to do:
```
const primaryDeviceKey = window.storage.get('primaryDevicePubKey');
const allOurDevices = await libloki.storage.getAllDevicePubKeysForPrimaryPubKey(
  primaryDeviceKey
);
```
which took long and was redundant because we have a limit of 1 device anyway, so i changed it to:
```
const ourNumber = textsecure.storage.user.getNumber();
const primaryDevice = window.storage.get('primaryDevicePubKey');
```
Thus `allOurDevices` would be `ourNumber` or `primaryDevice`

**Pull request merged**
